### PR TITLE
Log model / data through DagsHub DDA

### PR DESCRIPTION
**Pull request by timho102003**
# Describe the changes you've made

1. Log final model to remote server through DagsHub Direct Data Access (DDA)
2. Log raw data (train/test) and transformed data (if transform_target=True) through DasgHub DDA

# Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by jinensetpal — CHANGES_REQUESTED** [review]
Couple of changes:
1. Currently, we're tracking every additional entry using dvc, we need  to only track the folder.
2. We can use information from MLflow tracking to add repo owner, name, username and password/token; additional environment variables aren't required. Also, please setup a check for if branch option is provided, otherwise to default into 'main'.
3. Finally, authentication can be setup using DagsHub OAuth - it's what wandb is doing. I think that's the preferred implementation
4. Setup paths using Pathlib instead of just strings, otherwise compatibility breaks on non-*nix systems
5. This one is my bad - I pretty much mistook the scope of the integration; let's please shift to a DagsHub Logger that inherits from MLFlow Logger; since our implementation is external.

**Comment by timho102003** [comment]
1. Currently, we're tracking every additional entry using DVC, we need to only track the folder.  

The reason why only tracking each file instead of the folder:
- model: The model can be saved to any folder set by the user when calling save_model(), so if want to only track the artifacts folder, we'll have to save the model "again" to the local artifacts/model folder 
- data: The data will be saved into the random temporary folder automatically instead of setting by the user, so if we want to only track the artifacts folder, we'll have to save the data "again" to the local artifacts/data folder 

3. We can use information from MLflow tracking to add the repo owner, name, username, and password/token; additional environment variables aren't required. 
I don't understand this part as I'm also using the environ variable you mentioned in the DM, and those environ variable should be setup through dagshub.init() from dagshub/client

5. Finally, authentication can be setup using DagsHub OAuth - it's what wandb is doing. I think that's the preferred implementation
OAuth -> Do you mean install_hook()?
if yes, I don't see the difference between setting up the repo and OAuth

**Comment by jinensetpal** [comment]
1. The upload API specifies the path within which we save data. We don't need to copy to a path and then push, since we can specify the remote path. In either case, the entire directory only needs one .dvc pointer file.
3. I'm working on this, the integration is as you assumed in the sample ipynb.
4. `install_hooks()` is for data streaming, OAuth is only a part of it. Check out `dagshub.auth`, we'll be using that. It'll be a part of `dagshub.init` so I don't think it is something you need to worry about.

**Review by jinensetpal — APPROVED** [review]
LGTM!!

**Pull request merged**
